// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/0chain/s3migration/s3 (interfaces: AwsI)

// Package mock_s3 is a generated GoMock package.
package mock_s3

import (
	context "context"
	reflect "reflect"

	T "github.com/0chain/s3migration/types"

	gomock "github.com/golang/mock/gomock"
)

// MockAwsI is a mock of AwsI interface.
type MockAwsI struct {
	ctrl     *gomock.Controller
	recorder *MockAwsIMockRecorder
}

// MockAwsIMockRecorder is the mock recorder for MockAwsI.
type MockAwsIMockRecorder struct {
	mock *MockAwsI
}

// NewMockAwsI creates a new mock instance.
func NewMockAwsI(ctrl *gomock.Controller) *MockAwsI {
	mock := &MockAwsI{ctrl: ctrl}
	mock.recorder = &MockAwsIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAwsI) EXPECT() *MockAwsIMockRecorder {
	return m.recorder
}

// DeleteFile mocks base method.
func (m *MockAwsI) DeleteFile(arg0 context.Context, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteFile", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteFile indicates an expected call of DeleteFile.
func (mr *MockAwsIMockRecorder) DeleteFile(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteFile", reflect.TypeOf((*MockAwsI)(nil).DeleteFile), arg0, arg1)
}

// DownloadToFile mocks base method.
func (m *MockAwsI) DownloadToFile(arg0 context.Context, arg1 string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DownloadToFile", arg0, arg1)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DownloadToFile indicates an expected call of DownloadToFile.
func (mr *MockAwsIMockRecorder) DownloadToFile(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DownloadToFile", reflect.TypeOf((*MockAwsI)(nil).DownloadToFile), arg0, arg1)
}

// GetFileContent mocks base method.
func (m *MockAwsI) GetFileContent(arg0 context.Context, arg1 string) (*T.Object, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFileContent", arg0, arg1)
	ret0, _ := ret[0].(*T.Object)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFileContent indicates an expected call of GetFileContent.
func (mr *MockAwsIMockRecorder) GetFileContent(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFileContent", reflect.TypeOf((*MockAwsI)(nil).GetFileContent), arg0, arg1)
}

// ListFiles mocks base method.
func (m *MockAwsI) ListFiles(arg0 context.Context) (<-chan *T.ObjectMeta, <-chan error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListFiles", arg0)
	ret0, _ := ret[0].(<-chan *T.ObjectMeta)
	ret1, _ := ret[1].(<-chan error)
	return ret0, ret1
}

// ListFiles indicates an expected call of ListFiles.
func (mr *MockAwsIMockRecorder) ListFiles(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListFiles", reflect.TypeOf((*MockAwsI)(nil).ListFiles), arg0)
}
